### ISSUE TITLE
taRegisterTool should be defined in textAngularSetup

### ISSUE THREAD

**Issue by ocombe** [fraywing/textAngular#608] opened 2015-03-30 21:10 UTC
As explained here: https://github.com/ocombe/ocLazyLoad/issues/155#issuecomment-87831192, the constant `taRegisterTool` is used in the module `textAngularSetup`, but it is defined in the module `textAngular`.

The problem is that `textAngularSetup` doesn't require `textAngular` as a dependency, it's the other way around: `textAngular` requires `textAngularSetup` as a dependency.

This is a problem of circular dependency, `textAngularSetup` cannot use something defined in another module if it doesn't require it.

**Comment by SimeonC** [comment] 2015-04-02 02:10
I see, thanks for pointing it out I'll have to come up with something creative to fix it.

**Comment by JoelParke** [comment] 2015-09-18 21:51
<p>This is now fixed (I believe) See 2325dc9 or the next release.</p>

**Closed** 2015-09-18 21:52 UTC
Labels: bug

**Comment by vergil-lai** [comment] 2016-03-31 14:54
This issue fixed now? But I also happen that an error

**Comment by pbassut** [comment] 2016-03-31 15:05
@vergil-lai What error?

**Comment by vergil-lai** [comment] 2016-03-31 15:12
@pbassut [$injector:unpr] Unknown provider: taRegisterToolProvider <- taRegisterTool
In oclazyload 1.0.9 version of this error.

**Comment by pbassut** [comment] 2016-03-31 15:20
@vergil-lai Are you on version 1.5.0?

**Comment by vergil-lai** [comment] 2016-03-31 15:26
@JoelParke Yes.

**Comment by pbassut** [comment] 2016-03-31 15:31
@vergil-lai Looks like that still after #866 another dependency issue was introduced. Refer to #942 for more information.

**Comment by vergil-lai** [comment] 2016-03-31 15:59
@pbassut Thanks for the answer.These issues I have read, but did not solve the problem.


my code：


	angular.module('app')
	    .config([
	        '$ocLazyLoadProvider', function ($ocLazyLoadProvider) {
	            $ocLazyLoadProvider.config({
	                debug: true,
	                events: true,
	                modules: [				
						{
	                        name: 'textAngular',
	                        files: [
	                            'bower_components/textAngular/dist/textAngular.css',
	                            'bower_components/textAngular/dist/textAngular-rangy.min.js',
	                            'bower_components/textAngular/dist/textAngular-sanitize.min.js',
	                            'bower_components/textAngular/dist/textAngularSetup.js',
	                            'bower_components/textAngular/dist/textAngular.js'
	
	                        ],
	                        serie: true
	                    },
			});
        }
    ]);




	$stateProvider
		.state('app.product', {
        	url: '/product',
            templateUrl: 'views/product.html',
            resolve: {
                            deps: [
                                '$ocLazyLoad',
                                function($ocLazyLoad) {
                                    return $ocLazyLoad.load(['ui.select', 'textAngular']).then(
                                        function() {
                                            return $ocLazyLoad.load({
                                                serie: true,
                                                files: [
                                                    ...
                                            });
                                        }
                                    );
                                }
                            ]
                        }
                    })

**Comment by GiitRong** [comment] 2016-03-31 16:00
what?

**Comment by pbassut** [comment] 2016-03-31 16:02
@vergil-lai I'll use your code to reproduce the issue and fix it. Thanks for the info.

**Comment by vergil-lai** [comment] 2016-03-31 16:15
Thank you for your attention. In the main script loading textAngular  is normal. I'm curious why this error occurs in oclazyload.
best regards
