### ISSUE TITLE
source being stripped

### ISSUE THREAD

**Issue by beyondcreed** [fraywing/textAngular#847] opened 2015-08-17 22:28 UTC
Hello, if you go to your editor demo page, click source mode and paste the following:

```
         <h1 class="ui center aligned header">
            <i class="info letter circular icon"></i>
            About Us
         </h1>
```

Then go back to HTML mode, and again to source mode. Source is gone. Any ideas?

**Comment by beyondcreed** [comment] 2015-08-17 22:29
It seems empty ```<i></i>``` is the cause of source being removed. This used to work fine before, but something changed in more recent release.

**Comment by beyondcreed** [comment] 2015-08-17 22:52
We figured out another thing, its extra space in the front of the source causing it to be stripped.

**Comment by beyondcreed** [comment] 2015-08-17 22:54
So it's not the ```<i></i>``` its extra space at front, it's confirmed.

**Comment by pbassut** [comment] 2015-08-18 00:51
Does that happen here: [ textangular.com]( textangular.com)?
Cause I couldn't reproduce it

**Comment by beyondcreed** [comment] 2015-08-18 01:09
Correct, it happens on your live demo. Just copy and paste what I have above, then perform the switching. Screenshots below
![snapshot-space1](https://cloud.githubusercontent.com/assets/928851/9320098/05704644-450b-11e5-9805-893be548d268.png)
![snapshot-space2](https://cloud.githubusercontent.com/assets/928851/9320096/056bfcb0-450b-11e5-9a5d-6782c62737e5.png)
![snapshot-space3](https://cloud.githubusercontent.com/assets/928851/9320097/056ef0e6-450b-11e5-8b48-c7d18c0bb658.png)

**Comment by beyondcreed** [comment] 2015-08-18 01:10
For now we are removing spaces and comments, but this is not a very nice way to handle it. But we had to just get it working for our users.

**Comment by beyondcreed** [comment] 2015-08-18 15:51
did you have a chance to look into this btw? I think you pasted my old code example which I updated afterwards, make sure to paste in the above with leading spaces. thanks.

**Comment by pbassut** [comment] 2015-08-18 16:02
It doesn't happen here at all.
What browser are you using? I'm using chrome 44

**Comment by beyondcreed** [comment] 2015-08-18 16:11
tested on chrome Version 44.0.2403.155 m
tested on chromium Version 31.0.1650.63 (238485)

both of these are affected, just paste in the code with leading spaces as above screenshots show and then perform the switching. also we are seeing it in on safari and IE.

**Comment by pbassut** [comment] 2015-08-27 18:01
haha. Came to this issue again and tried to reproduce it. 
I didn't see the key information which was "leading spaces".
Thanks for this! And sorry for not paying attention.

Marking as a bug

**Comment by JoelParke** [comment] 2015-08-31 21:31
<p>It seems that we should handle the white space and keep the comments intact.  Perhaps keep the white space intact as well.  Looking into this.</p>

**Comment by JoelParke** [comment] 2015-09-01 06:01
<p>This is a test -- ignore.</p>

**Comment by JoelParke** [comment] 2015-09-01 07:32
<p>another test<br/></p>

**Comment by JoelParke** [comment] 2015-09-02 01:44
<p>I have fixed this and need some discussion around this fix before I produce a pullRequest.  <br/>I began by attempting to preserve the white space and any comments.  This turns our to be hard. <br/>What I <i>have</i> done is to remove the white space, which fixes the issue reported here.<br/></p><p><b>QUESTION:</b> </p><h3><i>Do the comments and white space need to be preserved?  Or is the issue only that the source vanished?  With what I have done, the white space is not preserved and to fix that is probably much harder. <br/></i></h3>

**Comment by JoelParke** [comment] 2015-09-02 01:44
<p>test</p>

**Comment by beyondcreed** [comment] 2015-09-02 03:13
We have already implemented same fix as you, we strip out spaces and comments as well. The problem with this is, if someone wants to edit source, it will look fairly weird and be harder to edit.

**Comment by chrisheninger** [comment] 2015-09-04 18:15
+1

Having this same issue and had been searching for the past bit (thought it was sanitization)... but minifying my HTML and trimming out the comments/whitespace results in correct behavior.

**Comment by JoelParke** [comment] 2015-09-04 21:16
Yes -- that makes it work.  I am looking at attempting to keep the white space and comments intact.

**Comment by JoelParke** [comment] 2015-09-18 19:25
See textAngular aba82651  -- this is fixed

**Closed by JoelParke** 2015-09-18 19:25 UTC
Labels: bug

**Comment by JoelParke** [comment] 2015-09-18 19:28
<p>See textAngular <a href="https://github.com/fraywing/textAngular/commit/aba826510f5356318673c622cfa55be512801581" class="commit-link" style="color: rgb(64, 120, 192);background-color: rgb(255, 255, 255);"><tt style="background-color: rgba(0, 0, 0, 0.0392157);">aba8265</tt></a> -- this is fixed and will be out in the next release....<br/></p>

**Comment by CraigAOliver** [comment] 2016-05-19 03:55
This issue appear to no longer be resolved.
We encountered it under 1.5.0 and it is currently repeatable  on [textangular.com](http://textangular.com) by following the step in the first comment of this issue or our particular issue is

this works
`<div class="fragment-container"><!-- SIDEBAR --><div class="sidebar" id="sidebar">  <nav>  <div class="grey-box">        <ul>          <li class="current"><a href="#what">What is</a></li>          <li><a href="#join">How do I join?</a></li>          <li><a href="#requesting">Requesting an?</a></li>          <li><a href="#creating">Creating an ?</a></li>          <li><a href="#admins">Adding admins</a></li>          <li><a href="#profile">My Profile</a></li>          <li><a href="#privacy">Privacy Settings</a></li>          <li><a href="#friends">Making Friends</a></li>          <li><a href="#messaging">Messaging</a></li>        </ul>      </div>    </nav>  </div>  <!-- PAGE -->  <div class="about-content">    <section class="content">      <section class="my-profile">        <h1><br></h1></section>    </section>  </div></div>`

this doesn't
`<div class="fragment-container">  <!-- SIDEBAR -->  <div class="sidebar" id="sidebar">  <nav>  <div class="grey-box">        <ul>          <li class="current"><a href="#what">What is</a></li>          <li><a href="#join">How do I join?</a></li>          <li><a href="#requesting">Requesting an?</a></li>          <li><a href="#creating">Creating an ?</a></li>          <li><a href="#admins">Adding admins</a></li>          <li><a href="#profile">My Profile</a></li>          <li><a href="#privacy">Privacy Settings</a></li>          <li><a href="#friends">Making Friends</a></li>          <li><a href="#messaging">Messaging</a></li>        </ul>      </div>    </nav>  </div>  <!-- PAGE -->  <div class="about-content">    <section class="content">      <section class="my-profile">        <h1><br></h1></section>    </section>  </div></div>`

The only difference are the spaces around the first comment.

**Comment by pbassut** [comment] 2016-05-20 15:01
@CraigAOliver Open a new issue for this. That should be relatively easy to solve.
