### ISSUE TITLE
Unable to paste text in editor with Chrome on Android

### ISSUE THREAD

**Issue by fgodet** [fraywing/textAngular#570] opened 2015-03-10 15:38 UTC
Hi,

Using your demo editor : http://textangular.com/
It is not possible to paste any text from an android phone (Android 4.2.2) using chrome (40-0.2214.109).
It simply does nothing. I tried using the js console by enabling usb debugging but nothing appears in the console ...
It does work on an iphone (chrome vers 40.0.2214.73).

**Comment by fgodet** [comment] 2015-03-10 16:49
I am still investigating but this could be because you use a contenteditable attribute ...

**Comment by SimeonC** [comment] 2015-03-10 21:19
Looks like contenteditable is supported, if you can type then it's a paste issue not contenteditable: http://caniuse.com/#feat=contenteditable.

If it's just paste I'd guess it's something to do with this code here: https://github.com/fraywing/textAngular/blob/master/lib/taBind.js#L398-L441

I don't own an android so I can't really help test this one, if you do find the cause let us know or throw up a PR and well see what we can do.

**Comment by fgodet** [comment] 2015-03-11 11:57
Thx for your fast response and for pointing me to the right direction.
I fixed the issue by adding 
{code}
  && clipboardData.types.length > 0 // line 1379
{code}
Indeed, clipboardData is defined but types are empty when pasting.
With this fix, we make sure pasted content is handled in your else condition.
Another working solution was to use setTimeout to the whole function but then, content is not cleanup and call processPaste with an empty text (but in frontend, content get pasted).

**Comment by fgodet** [comment] 2015-03-11 15:50
I also fixed a weird behavior : pasting was working but focus was not properly triggered. Focusing first and removing the temporary div after solved that.

**Comment by SimeonC** [comment] 2015-03-15 23:22
Fixed via your PR in v1.3.10 I believe, thanks.

**Closed by SimeonC** 2015-03-15 23:22 UTC
