### ISSUE TITLE
updateSelectedStyles not called initially

### ISSUE THREAD

**Issue by TheWizz** [fraywing/textAngular#1241] opened 2016-07-19 07:52 UTC
My app creates its toolbar dynamically, as needed. This generally works well, but fails to set the initial state of tools when those are created and added to the DOM. This results in active tools _not_ being marked with the "active" class until some action occurs.

This behavior is managed by the updateSelectedStyles function in the textAngular directive, which is dutifully called on various kinds of key and mouse events. Hence, I can make the tools appear correctly by simply pressing the shift key once (as doing so triggers a keydown event, which is then calling updateSelectedStyles).

It seems to me that updateSelectedStyles should be called _once_ initially, soon after creating the toolbars, to make sure that the initial state is correct. After this, calling on the various key/mouse events that may alter the text or the selection should suffice.

FYI, I currently work around this bug by the following hack in my code:

```
	// Ugly hack to set initial state of editing tools
	var taScope = angular.element(toEdit).scope();
	taScope.updateSelectedStyles();
	this.scope.$apply();
```

As you can see, I obtain the scope through the element representing the edited div and then calls updateSelectedStyles on it, followed by $apply to make it "take".

-JM

**Comment by JoelParke** [comment] 2016-07-19 21:06
Thanks JM. 

I believe that what you need to do is to simply do:
textAngularManager.retrieveEditor('jm').updateSelectedStyles();

That should take care of all the initialization that you need in this instance.
Please let me know how that works out.... so I can proceed.  THANKS!

I may add a function textAngularManager.updateSelectedStyles() but that seems a bit over the top, although it does give a nice place to put the DOCS.

**Comment by TheWizz** [comment] 2016-07-19 21:23
Thanks for the suggestion. Perhaps I wasn't too clear in my original posting. What I _really_ meant was that I think textAngular _itself_ should call updateSelectedStyles once initially _all by itself_ after connecting the toolbar to an editor. And not only call it in response to various kinds of key and mouse events. I hope this makes sense.

-JM

**Comment by JoelParke** [comment] 2016-07-19 21:52
I understood what you were possibly suggesting.  I'm still thinking about that and the app flow. ... give me a few...

**Comment by JoelParke** [comment] 2016-07-20 00:00
The problem is that it is not clear where this automatic updateSelectedStyles() should happen.  For example: in my code (another project).  The toolbar is modified by adding additional tools that are registered with taRegisterTool().  So any automatic code in this case would have to be done inside the taRegisterTool() which doesn't yet live inside of any html.  

In the end, it seems it is probably best to add a function to textAngularManager: updateStyles() where the app can explicitly ask for this update in those instances where it is needed.   Thoughts?

**Comment by TheWizz** [comment] 2016-07-20 06:26
Yes, adding updateStyles to textAngularManager seems like a clean waya to hanle it in cases where the autmatically performed updateStyles don't suffice. 

However, it still feels like there should be some place were updateStyles gets called _once_ initially, after connecting a toolbar to an editor, just to give things a changce to sync up front. As of now, it seems updateStyles is _only_ called in response to mouse and key events.

-JM

**Comment by JoelParke** [comment] 2016-07-21 19:37
I'm considering this.... Perhaps a modified at time check and an event to do this in the future... maybe...

**Comment by JoelParke** [comment] 2016-07-22 05:28
I have checked into my branch code that will make this happen in a good way.
I have added the new updateStyles() call, which will be automatically called.
Can you take a look at these changes and see if this resolves your issue?
See: https://github.com/fraywing/textAngular/pull/1234/commits/d373fe10e770bf521641975cbc6a4f480d0a1f9e

Thanks,
Joel Parke

**Comment by JoelParke** [comment] 2016-07-22 05:44
To make this check easier, I checked both this enhancement and the fix for scopes leaking memory into the master branch.  So that if you just pull the main source you can do:
grunt, which will test and build the dist, so you can test.

**Comment by TheWizz** [comment] 2016-07-22 09:28
I tested this with my app, and it seems to work fine. I no longer have to call updateStyles() manually from my code. Many thanks for looking into this.
-JM

**Comment by JoelParke** [comment] 2016-07-22 18:03
Good -- thanks very much for checking.  The one issue I have left here is that I don't force a $apply when I do the $interval... and I'm not sure that is necessary.  I don't think so and would rather not constrain it if I don't need to.  Any opinion on that?

**Comment by TheWizz** [comment] 2016-07-22 20:48
Well, just updating model state (which seems to be what updateSelectedStyles does) without calling $apply, will fail to update the UI. At least until something else is causing $apply to be called, which apparently happens in my case. Why would you _not_ want to have $interval perform invokeApply? Unless something else calls $apply after your deferred updateSelectedStyles call, your improved functionality here may actually fail to update the UI, as far as I can tell, which was the whole point of this exercise. 

All IMHO, of course, as I may very well overlook something here.

-JM

**Comment by JoelParke** [comment] 2016-07-23 19:52
<p>It is simply a question of maximizing the efficiency of the code in general.  If I call $interval with the default settings it will do an $apply automatically and that is what I will probably do.  But in the interest of fully understanding, I really want to know WHY it works in your case, the way the code is now:</p><pre style="background-color: #ffffff;color: #000000;"><span style="color: #458383;">triggerIntervalTimer </span>= $interval(<span style="color: #000080;"><b>function</b></span>() {<br/>   <i>updateStyles</i>();<br/>   <span style="color: #458383;">triggerIntervalTimer </span>= <span style="color: #660e7a;"><b>undefined</b></span>;<br/>}, <span style="color: #458383;">triggerInterval</span>, <span style="color: #0000ff;">1</span>, <span style="color: #000080;"><b>false</b></span>); <span style="color: #808080;"><i>// only trigger once</i></span></pre><p>So the question is why DON'T I need to make this call with </p><pre>$interval(<b>function</b>() { ... }, triggerInterval, 1);</pre><p>In your case???? What is already triggering the $digest.  and it it will already always be happening then there is no need to make a change.</p><p>Perhaps you can determine why.  In my code, I don't need to use the code I added anyway so it's hard to know. </p>

**Comment by JoelParke** [comment] 2016-07-23 19:54
<p>In either case I may well change this to the default case anyway, but in the interest of understanding it would be great to know why the $apply is now needed in your case.</p>

**Comment by TheWizz** [comment] 2016-07-23 21:00
I agree. Something else in my setup is calling $apply. I've noticed that often just moving the mouse triggers $apply. I haven't tracked down exactly where and why. 

But I agree that the proper behavior in textAngular should be to call the "applying" version of $interval if the callback changes model state (which it does), and not assuming that someone else soon will call $apply. Besides, this happens only _once_ after connecting a toolbar, as far as I understand, so it shouldn't be a performance problem.

-JM

**Comment by JoelParke** [comment] 2016-07-24 03:03
Thanks for your thoughts.  I agree and will make the change to insure that $apply is invoked.

**Closed** 2016-07-25 23:51 UTC
Labels: enhancement, Resolved with PR
