### ISSUE TITLE
How to get rid of duplicating content inside <p>

### ISSUE THREAD

**Issue by alyrik** [fraywing/textAngular#1205] opened 2016-06-06 14:21 UTC
I'm using custom buttons to insert videos and presentations (with `iframe`). It's inserted in such way: 
```
var embed = '<span class="project-text__video" src="' + videoId + '"><iframe width="560" height="315" src="//www.youtube.com/embed/' + videoId + '" frameborder="0" allowfullscreen></iframe></span>';

restoreSelection();
textAngular.$editor().wrapSelection('insertHTML', embed, true);
```

Everything is OK. But pressing Enter (when caret is inside that inserted block) causes its duplication.

![screen shot 2016-06-06 at 17 12 22](https://cloud.githubusercontent.com/assets/10388022/15824995/9c50a90a-2c0a-11e6-8e96-176a8999eb7e.png)

How to handle this? I want it to create new empty `<p>` but not to duplicate inner content.

**Comment by stevokk** [comment] 2016-06-07 12:35
Maybe a plunkr demo here would clear up the behaviour you're describing and allow people to track down why this is happening.

**Comment by alyrik** [comment] 2016-06-07 14:32
@stevokk, here's a [plunkr](http://plnkr.co/edit/Cg3lhobEC3YnHNKefbGx?p=preview)

Try to add a video (press a button). When the video is added try to set caret right on that block with a player (before it). Then press Enter. You'll see that `<p class="project-text__video">` is duplicating right above the video block.

**Comment by alyrik** [comment] 2016-07-01 08:00
There is one workaround: just change embed tree's structure:

```
var embed = '<p><span src="' + videoId + '"></span><iframe width="560" height="315" src="//www.youtube.com/embed/' + videoId + '" frameborder="0" allowfullscreen></iframe></p>';
```

**Comment by JoelParke** [comment] 2016-07-17 05:03
I am assuming that this is the same with the 1.5.2 release, but could you verify?  As I wasn't able to reproduce.  Thanks!

**Comment by gregory-h** [comment] 2016-08-11 15:40
I can confirm this with 1.5.3 and it's a serious issue for us.  

We're using insertHtml to inject content of the form '<span>..</span>', and If I view the markup directly after doing an insert it looks like this 
<p><span class="user-view client.firstName">Client First Name</span><br></p>

The problem is that immediately after doing an insert anything typed goes into my span text, ie 
<p><span class="user-view client.firstName">Client First Name and typed text</span><br></p>

Pressing enter duplicates the injected html but with empty text
<p><span class="user-view client.firstName">Client First Name and typed text</span><br></p>
<p><span class="user-view client.firstName"></span><br></p>

If I save the markup and open it again in the editor it edits normally; as a workaround is it possible for me to programattically force the editor to re-render after calling insertHtml?

**Comment by JoelParke** [comment] 2016-09-05 21:14
<p>I see the issue and am investigating.  Sorry that it took so long to get to this one.... <br/>Joel</p>

**Comment by JoelParke** [comment] 2016-09-09 00:51
<p>It turns out that the issue isn't any difference between the html and the text view.  That does exist and I am working to remove that if I can without breaking anything else.</p><p>But it seems that rangy doesn't really allow you to select something that is not visible.  For example I attempted changing:<br/></p><pre style="background-color: #ffffff;color: #000000;"><span style="color: #458383;">embed </span>= <span style="color: #008000;"><b>'&lt;span&gt;&lt;/span&gt;&lt;span class=&#34;project-text__video&#34; src=&#34;' </b></span>+ <span style="color: #458383;">videoId </span>+ <span style="color: #008000;"><b>'&#34;&gt;&lt;iframe width=&#34;560&#34; height=&#34;315&#34; src=&#34;//www.youtube.com/embed/' </b></span>+ <span style="color: #458383;">videoId </span>+ <span style="color: #008000;"><b>'&#34; frameborder=&#34;0&#34; allowfullscreen&gt;&lt;/iframe&gt;&lt;/span&gt;'</b></span>;<br/></pre><p>but that didn't help , but the following gets you much closer to what you want...<br/><br/></p><pre style="background-color: #ffffff;color: #000000;"><span style="color: #458383;">embed </span>= <span style="color: #008000;"><b>'&lt;span&gt;&amp;#65279;&lt;/span&gt;&lt;span class=&#34;project-text__video&#34; src=&#34;' </b></span>+ <span style="color: #458383;">videoId </span>+ <span style="color: #008000;"><b>'&#34;&gt;&lt;iframe width=&#34;560&#34; height=&#34;315&#34; src=&#34;//www.youtube.com/embed/' </b></span>+ <span style="color: #458383;">videoId </span>+ <span style="color: #008000;"><b>'&#34; frameborder=&#34;0&#34; allowfullscreen&gt;&lt;/iframe&gt;&lt;/span&gt;'</b></span>;<br/></pre><p>where the &amp;#65279; is a zero space 'space' which allows you to type into that &lt;span&gt;.  I also changed the taSelection.getSelection() code slightly in this case, and I have more to look at tomorrow.<span>  </span><br/></p><p><br/></p><p><br/></p>

**Comment by JoelParke** [comment] 2016-09-10 00:48
I have a PR that I am going to check-in later today.  Basically you will need to put a:
`&#62579;`
before your html that you will embed. 
For example:
```
    var embed = '&#65279;<p class="project-text__video" src="' + videoId + '"><iframe width="560" height="315" src="//www.youtube.com/embed/' + videoId + '" frameborder="0" allowfullscreen></iframe></p>';
                            
   OR
 
     var embed = '&#65279;<span class="project-text__video" src="' + videoId + '"><iframe width="560" height="315" src="//www.youtube.com/embed/' + videoId + '" frameborder="0" allowfullscreen></iframe></span>';

```
work well now.  As soon as I put the code out there, please check and verify!!  
This was a pain because it is the browser that does the real work.

**Comment by JoelParke** [comment] 2016-09-10 00:55
After testing I see that this works fine on Chrome, but NOT on Firefox, so it will take a bit more time &*^%&*( ;-).

**Comment by JoelParke** [comment] 2016-09-14 18:12
<p>I have code with:</p><pre style="background-color: #ffffff;color: #000000;"><span style="color: #458383;">embed </span>= <span style="color: #008000;"><b>'&lt;span&gt;&amp;#65279;&lt;/span&gt;&lt;span class=&#34;project-text__video&#34; src=&#34;' </b></span>+ <span style="color: #458383;">videoId </span>+ <span style="color: #008000;"><b>'&#34;&gt;&lt;iframe width=&#34;560&#34; height=&#34;315&#34; src=&#34;//www.youtube.com/embed/' </b></span>+ <span style="color: #458383;">videoId </span>+ <span style="color: #008000;"><b>'&#34; frameborder=&#34;0&#34; allowfullscreen&gt;&lt;/iframe&gt;X&lt;/span&gt;'</b></span>;<br/></pre><p>working well.  But I also noticed that the ngModel is not updated with the correct html... so... a bit more.</p>

**Comment by JoelParke** [comment] 2016-09-14 19:45
<p>I just merged in PR and believe this fixes this issue.  PLEASE test and left me know.  This was a royal pain, but I like the behavior now.  Closing this issue. please reopen in needed.</p>

**Closed** 2016-09-14 19:49 UTC
Labels: bug, Resolved with PR
