### ISSUE TITLE
Cannot paste text in Internet Explorer 11

### ISSUE THREAD

**Issue by anitin** [fraywing/textAngular#298] opened 2014-08-29 16:55 UTC
Hi fraywing,

I am trying to use textangular (version 1.2.2) on Internet explorer 11. But I cannot paste any text in textangular.

I even tried this on textangular.com and it seem to be broken.

Can you please look into this?

Thanks
Ankit

**Comment by notatestuser** [comment] 2015-01-13 14:54
Any chance of a backport of this fix to 1.2?

**Comment by SimeonC** [comment] 2015-01-13 21:02
Unfortunately not - it's a rather large and involved piece of code and a lot of the pre-releases have other fixes for this issue.

**Comment by thynctank** [comment] 2015-05-29 06:14
I should've posted on here before, but just now found the latest version of textAngular in npm (1.4.1) still doesn't support paste in IE11.

From re-reading this thread again, I'm not totally clear, @SimeonC:  is textAngular simply not supporting IE11 altogether right now, or does it require Angular 1.3+ to support it, or what?

We were able to fix the issue by forcing IE11 into IE9 mode via the meta as suggested here and elsewhere, but our application needs to leverage some newer APIs that IE11 supports (File mainly) but shifting IE11 into IE9 document mode removes the APIs, since they didn't exist in IE9.

We still need to support IE8 as of now, so shifting to Angular 1.3 has not been an option so far.

Thanks in advance for your help, and thanks for textAngular in general, it's very simple to use and very customizable, which is appreciated.

**Comment by thynctank** [comment] 2015-05-29 14:26
Hmm... the plunker you link to from the readme works in IE11, and it is using Angular 1.2. I feel like I just need to find the magical combination that will work for me...

Has anyone got more insight into this?

**Comment by thynctank** [comment] 2015-06-01 16:49
Quick update: dropping down to 1.3.7, paste works again for me in IE11.

Just note that there will likely be CSS tweaks if you've customized your code much. Blue halos inside the perceived text box in Chrome and overflow issues are all that I've taken note of, but just started with this.

**Comment by aravindaran** [comment] 2015-06-18 10:10
I have added the code ..but it is not working

**Comment by noobd3v** [comment] 2016-08-26 06:52
still not working on IE please reopen the issue.

**Comment by noobd3v** [comment] 2016-08-26 07:05
It is a length issue when i tried copying html of length 1017 it worked fine but was not able to save html with length of 1647.

**Comment by JoelParke** [comment] 2016-12-05 06:05
<p>Could you re-test and post a test case if still broken, so I can fix this??? Thanks!!</p><p>I have tested this on MS edge and and least the pasting issue I cannot reproduce.  Please re-open and report if there is still a length issue.  But I am closing this for now.  -- closed --</p>

**Closed** 2016-12-24 22:10 UTC
Labels: bug, Need more info
