### ISSUE TITLE
Cant paste valid html in html mode.

### ISSUE THREAD

**Issue by michalturak** [fraywing/textAngular#1383] opened 2016-10-28 11:06 UTC
Hello,

Im trying to paste some html:
"<a style="background-color: rgb(255, 255, 255);" href="https://www.google.pl" target="_blank">google</a>"

and its not working, TextaAngular acts weird because when i switch back to rich text editor, i still see old rendered html and model.

Steps to reproduce:
1. Open http://textangular.com/
2. switch to html mode
3. replace all with `<a style="background-color: rgb(255, 255, 255);" href="https://www.google.pl" target="_blank">google</a>`
4. switch back to rich text
5. nothings changed and model value is not updated

**Comment by JoelParke** [comment] 2016-10-28 16:08
<p>Seems to be a very clear bug.  I will try and look at this later today.</p>

**Comment by thenickofnicks** [comment] 2016-10-29 10:30
For me, the issue seems to lie in the taFixChrome factory.  I had to override the factory with a decorator and remove the lines that are stripping styles tags.  The sanitization seems imperfect and there is no error catching on fail of the angular sanitize function.

We don't need that much sanitization as we control the input and trust the source.  Maybe there could be an option to disable this type of sanitization in the future, as inline styles are needed in my application and cannot be stripped.

After chrome sanitization <a style="background-color: rgb(255, 255, 255);" href="https://www.google.pl" target="_blank">google</a> becomes <ahref="https://www.google.pl" target="_blank">google</a> and this causes an error which is not caught.

**Comment by michalturak** [comment] 2016-11-22 11:13
Any chances this will be fixed soon?

**Comment by JoelParke** [comment] 2016-12-01 15:34
<p>I will try and look at this in the next couple of days...</p>

**Comment by JoelParke** [comment] 2016-12-03 01:47
<p>How important is the style=&#34;background-color: ...;&#34; addition that you are making?<br/>The issue is that I don't have a good test set for what Chrome adds and folks are expecting to be removed.  I have fixed the code so that it only strips out some styling as before.  And the html is fine - but the styling is gone.  </p><p>We could add a flag to disable this type of styling removal for just the taFixChrome factory, but I would rather get rid of all that I can and not add another flag. <br/>Please let me know your thoughts.  This would be easier if I knew better what junk Chrome still dumps into the html. <br/>I will think about this some more.  </p>

**Comment by JoelParke** [comment] 2016-12-03 17:27
I have checked in a PR #1411 which fixes the breakage.  But the styles are still removed.  I am awaiting your feedback https://github.com/michalturak.  Thanks!

**Comment by michalturak** [comment] 2016-12-03 17:38
Hi,

For me style="background-color: ...;"  is not important, but some users are pasting hmtl from other sources and they are encountering this bug, and its hard then to analyze html for them, especially when its look valid.

The styles can be removed, its not big problem for user when he paste html and see a bit different html, so big thanks for fixing this!

**Comment by JoelParke** [comment] 2016-12-03 19:27
In the end, I added a ts-keep-styles attribute that allows one to tell taFixChrome to keep these styles.  This will probably benefit others and perhaps your users.  PR #1412 
Also the Wiki is updated with:
`taKeepStyles: Normally when html is pasted into the editor, taFixChrome removes the following styles: 
[font-family: inherit, line-height: color: inherit, color: rgb(#{3}), background-color: rgb(#{3})] 
But when taKeepStyles === "true", these are kept.`

**Closed by JoelParke** 2016-12-03 19:27 UTC
Labels: bug
