### ISSUE TITLE
Copy Paste from IE brings in Javascript and other tags as well

### ISSUE THREAD

**Issue by barathank** [fraywing/textAngular#533] opened 2015-02-02 18:33 UTC
Copy and paste from IE to Textangular Editor is copying the Javascript and CSS. Please fix this ASAP.
For example copy and pasting the contents from following wiki page copies some junk character as well. http://en.wikipedia.org/wiki/Lift-induced_drag

**Comment by SimeonC** [comment] 2015-02-02 21:05
Interesting, it looks like this is not an IE issue, seems like the sanitiser is doing something not quite right here as it should be stripping out style and script tags anyway. Will investigate!

**Comment by SimeonC** [comment] 2015-02-02 21:17
Though I will add, this is Open Source software, if you really need it done ASAP your choices are pay me (I'm a contractor you see) or create a PR following the [guidelines](https://github.com/fraywing/textAngular/blob/master/CONTRIBUTING.md).

**Comment by barathank** [comment] 2015-02-02 21:49
Thanks for your Quick response. Sorry to use ASAP in my comment, i did not mean what i meant. It is good to know you are a independent contractor as well. Will let you know if we need any help apart from textangular.

**Comment by SimeonC** [comment] 2015-02-02 21:55
It's Ok. I was just saying it as I'm about to start a big project that should keep me busy with little time for textAngular for the next month or so. So ASAP may not be as soon as you like/need.

**Comment by SimeonC** [comment] 2015-02-03 04:24
I've just reproduced this as an Angular.js bug!! http://codepen.io/anon/pen/pvWWjz, AngularJS Issue https://github.com/angular/angular.js/issues/10943

**Comment by barathank** [comment] 2015-02-03 19:29
Thanks for the update, are you available to work from New York area?

**Comment by SimeonC** [comment] 2015-02-03 21:05
I'm actually based in New Zealand and can work remotely - the timezone difference wasn't too much of an issue last time I worked with someone over in New York.
If you want to talk about contracting me it's best to use the email address in my [github profile](https://github.com/SimeonC).

**Comment by SimeonC** [comment] 2015-02-03 23:40
They posted up a fix for this in the main angular issue. I've committed it up so you can grab the sanitiser from the master version or just wait till next patch comes around.

**Closed** 2015-02-03 23:41 UTC
Labels: bug
