### ISSUE TITLE
Output for plaintext in first line (RTE) is not generating properly.

### ISSUE THREAD

**Issue by souravbadami** [fraywing/textAngular#1134] opened 2016-04-02 08:10 UTC
**Overview of the issue** - While typing plain text in first line on RTE, the output is not generated.
**Angular Version(s)** - 1.5.0
**Browsers and Operating System** - Mozilla Firefox 45.0 / Ubuntu 14.04
**Reproduce the error** - Visit http://textangular.com/ and type some plain text, say "abc".

**Comment by pbassut** [comment] 2016-04-02 23:46
I don't understand. What's RTE?
What's the expected behaviour when typing abc in it?

**Comment by seanlip** [comment] 2016-04-03 01:34
To reproduce:
  1. On Firefox (I use Firefox v44.0), go to textangular.com.
  2. In the "Editor demo" section, click in the rich-text editor, and type Ctrl-A to select everything in it, then press the Delete key to clear all the contents.
  3. Type "abc".
  4. Look at the "HTML output" section below the editor demo; it is blank. This shouldn't happen -- it should instead be `<p>abc</p>`.

Note: Pressing the Enter key and typing something else causes the HTML output to be generated on every keystroke (which I think is the expected behaviour).

**Comment by vlad-ya** [comment] 2016-04-08 17:22
Doesn't work for me as well

Firefox 45.0.1
OS X 10.11.4

**Comment by souravbadami** [comment] 2016-04-08 17:48
@pbassut , As stated above, RTE: Rich Text Editor. The problem occurred since version 1.4.6. Conflict point ~ fraywing/textAngular@5884b83

**Comment by pbassut** [comment] 2016-04-08 18:34
![image](https://cloud.githubusercontent.com/assets/1500037/14393837/6337d66e-fd9f-11e5-9b7c-f379f7e1e077.png)
I can't reproduce it.

**Comment by pbassut** [comment] 2016-04-08 18:36
Right, the issue is on firefox only. We've got some other things with firefox.
Thanks for the report.

**Comment by JoelParke** [comment] 2016-07-30 18:58
I believe this is resolved with PR #1259
Could you please check and close???

**Closed** 2016-08-06 18:47 UTC
Labels: bug, Resolved with PR

**Comment by souravbadami** [comment] 2016-08-06 18:48
@JoelParke -- I missed the thread somehow. Anyways, It's solved now. Thanks!
