### ISSUE TITLE
html mode source being cleared

### ISSUE THREAD

**Issue by CraigAOliver** [fraywing/textAngular#1187] opened 2016-05-22 23:13 UTC
@beyondcreed as requested new issue.
Thanks

Referencing issue #847 
This issue appear to no longer be resolved.

If you go to your editor demo page, click source mode and paste the following:

         <h1 class="ui center aligned header">
            <i class="info letter circular icon"></i>
            About Us
         </h1>
Then go back to HTML mode, and again to source mode. Source is gone. Any ideas?

We encountered it under 1.5.0 and it is currently repeatable on textangular.com by following the step in the first comment of this issue or our particular issue is

this works
`<div class="fragment-container"><!-- SIDEBAR --><div class="sidebar" id="sidebar"> <nav> <div class="grey-box"> <ul> <li class="current"><a href="#what">What is</a></li> <li><a href="#join">How do I join?</a></li> <li><a href="#requesting">Requesting an?</a></li> <li><a href="#creating">Creating an ?</a></li> <li><a href="#admins">Adding admins</a></li> <li><a href="#profile">My Profile</a></li> <li><a href="#privacy">Privacy Settings</a></li> <li><a href="#friends">Making Friends</a></li> <li><a href="#messaging">Messaging</a></li> </ul> </div> </nav> </div> <!-- PAGE --> <div class="about-content"> <section class="content"> <section class="my-profile"> <h1><br></h1></section> </section> </div></div>`

this doesn't
`<div class="fragment-container"> <!-- SIDEBAR --> <div class="sidebar" id="sidebar"> <nav> <div class="grey-box"> <ul> <li class="current"><a href="#what">What is</a></li> <li><a href="#join">How do I join?</a></li> <li><a href="#requesting">Requesting an?</a></li> <li><a href="#creating">Creating an ?</a></li> <li><a href="#admins">Adding admins</a></li> <li><a href="#profile">My Profile</a></li> <li><a href="#privacy">Privacy Settings</a></li> <li><a href="#friends">Making Friends</a></li> <li><a href="#messaging">Messaging</a></li> </ul> </div> </nav> </div> <!-- PAGE --> <div class="about-content"> <section class="content"> <section class="my-profile"> <h1><br></h1></section> </section> </div></div>`

The only difference are the spaces around the first comment.

Thanks

**Comment by JoelParke** [comment] 2016-07-29 07:02
This is still as issue with v1.5.3, but I believe I know what the issue is... 
I will get to it in a day...
Thanks for the clear info!

**Comment by JoelParke** [comment] 2016-07-30 18:58
I believe this is resolved with PR #1259
Could you please check and close???

**Closed** 2016-08-06 18:45 UTC
Labels: bug, Critical, Resolved with PR

**Comment by CraigAOliver** [comment] 2016-08-19 02:12
Thank you @JoelParke and @pbassut 
I've verified this issue is resolved (tested under 1.5.6-0)
