### ISSUE TITLE
wrapSelection only working every second call - selection is lost

### ISSUE THREAD

**Issue by mrjamesriley** [fraywing/textAngular#753] opened 2015-06-19 13:02 UTC
Hello all,

I'm seeing an issue where calling `wrapSelection` on an editor retrieved via `textAngularManager` is only working on every second call. It seems on the times where it does not work, the focus is being lost immediately as a button is clicked. 

I've created a small example on Plunker here:
http://plnkr.co/edit/1SzKXsJmXYHG6g0cKzUm

The issue can be recreated with the following steps:

1. double click a word to select it, then click 'Color' - you'll see the word turn red
2. double click on another word, then click 'Color' - you'll see no change
3. double click on third word, then click 'Color' and you'll see the word turn red
.... and so on

Note: I'm seeing this on Chrome and Safari, but not on Firefox.

I'm working through the Rangy/textAngular source code but feel a long way off an answer just yet.

cheers,
James

**Comment by bytasv** [comment] 2015-06-25 11:43
:+1: I'm having the exact same problem... it kinda makes editor unusable or very frustrating to use

**Comment by bytasv** [comment] 2015-06-25 11:44
Also seems to be the same issue: https://github.com/fraywing/textAngular/issues/606

**Comment by jdolan** [comment] 2015-06-29 19:53
:+1: I'm resolving the editor via `textAngularManager.retrieveEditor('my-editor')` and then calling `editor.scope.wrapSelection("insertHTML", "some markup", true);` The first time this is invoked, nothing happens. The second time, it works. Third time, nothing. Forth time, works, etc..

**Comment by pbassut** [comment] 2015-07-04 15:51
As pointed out by @bytasv. This is a duplicate of #606.

**Closed** 2015-07-04 15:51 UTC
Labels: duplicate
