### ISSUE TITLE
Image src is re-requested each time the editor loses focus

### ISSUE THREAD

**Issue by Eutropia** [fraywing/textAngular#219] opened 2014-06-17 20:28 UTC
Overview of the issue - 
I created a custom image insertion tool based off the one in the source, using <code>"textAngular.$editor().wrapSelection('insertImage', imageLink, true);" </code>
(the default prompt style left something to be desired, so I created a modal, I also needed upload capability.)
Anyways, I noticed that after the image was in the text box, it was reloading after the editor loss focus.  And indeed, a separate network requestion was being fired for each time it lost focus, unless the image was still loading.

Motivation for or Use Case - The image shouldn't reload.  There's no reason to hammer anyone's servers once you already have the image.
Angular Version(s) - is it a regression?
<code>"dependencies": {
        "es6-shim": "~0.9.2",
        "d3": "~3.4.4",
        "jquery": "~2.1.0",
        "angular": "1.2.16",
        "angular-cookies": "1.2.16",
        "angular-sanitize": "1.2.16",
        "angular-animate": "1.2.16",
        "angular-ui-router": "0.2.10",
        "angular-motion": "~0.3.2",
        "angular-strap": "~2.0.0",
        "restangular": "~1.3.1",
        "textAngular": "1.2.1-pre1",
        "fontawesome": "4.1.0",
        "ng-file-upload": "~1.3.1",
        "bootstrap-sass-official": "v3.1.1",
        "cornelius": "restorando/cornelius#995ac0f0cc8533e35050a6d04de87191c303aceb",
        "ngstorage": "~0.3.0",
        "angular-rx": "~0.0.3",
        "ng-flow": "~2",
        "angular-raven": "~0.5.6",
        "raven-js": "~1.1.15"
    },
    "devDependencies": {
        "angular-mocks": "1.2.16",
        "angular-scenario": "1.2.16"
    },
    "resolutions": {
        "angular": "1.2.16"
    }
}</code>
Browsers and Operating System - I develop on chrome, so it's an issue if chrome is doing it..

Reproduce the error - Not sure if it's isolated enough for me to recreated on a plunkr on this time, maybe later this week.  As of now it's: Insert an image, click outside the editor, image is re-requested.

Suggest a Fix - It might be an interaction with rangy?  Whenever this happens, it happens right after a dom-subtree modification on the text box in the editor.

Thanks so much for this wonderful editor by the way, great work!

**Comment by pbassut** [comment] 2015-08-04 15:29
I couldn't reproduce this issue. Looks like it was fixed somehow.
I'm closing it. 
I'll reopen if requested.

**Closed by pbassut** 2015-08-04 15:29 UTC
Labels: bug, Needs Reproduction Example

**Comment by venkateswarlunalabolu** [comment] 2017-09-25 10:05
at the time of drag and drop the image. how to add alt option in image tag
