### ISSUE TITLE
Unable to type in the "ż" Polish letter

### ISSUE THREAD

**Issue by cfjohnston** [fraywing/textAngular#518] opened 2015-01-28 16:49 UTC
Using texAngular version v1.3.0-pre14, I'm unable to type the "ż" Polish letter.  It performs an undo action, removing charcters that were previously typed, instead of adding the ż.  It can be pasted in, but we need to be able to type it in since there are many Polish words with this letter and it's not an acceptable work around to paste it every time.  I also tried upgrading to the latest version 1.3.3. and still see the problem.  I am using Windows 7, and tried on IE 10, Chrome 40.0.2214.93, and FF 31.4.0 ESR.

Steps:
1) Install the Polish (Programer) keyboard.  Following instructions at http://blogs.msdn.com/b/saveenr/archive/2009/05/17/typing-polish-accented-characters-on-a-us-keyboard.aspx
2) I was able to type Polish "Ż" and "ż" in Notepad, but not in a textAngular field

I see some similar issues in other projects at these links:
http://www.tinymce.com/forum/viewtopic.php?id=783
https://github.com/xing/wysihtml5/issues/16
https://tracker.moodle.org/browse/MDL-47133

Any thoughts on this?

**Comment by SimeonC** [comment] 2015-01-28 20:06
OK, it seems that the issue is simply based around checking that the alt key is not pressed in the undoManager. Looks like a simple fix but I'll need some time to do it.

As a side note, 1.3.0 has an official release now!

**Comment by cfjohnston** [comment] 2015-01-28 21:21
Ok, thanks.  I will await an update.

**Comment by tpcyang** [comment] 2015-02-10 03:59
Hi, would it be possible to have a target date for this bug?
Thanks a lot !!

**Comment by SimeonC** [comment] 2015-02-10 04:02
Hmmm, it should be fixed in 1.3.6. Not sure how I managed to slip that past the changelog/commits process.

https://github.com/fraywing/textAngular/blob/v1.3.6/lib/taBind.js#L455

Can someone confirm this fixes it please?

**Comment by akupiec** [comment] 2015-02-10 13:05
Hi, I just upgraded textAngular form 1.2.2 to 1.3.6, and "ż" don't work any more ;)

**Comment by SimeonC** [comment] 2015-02-10 21:23
Hmm, thanks for letting me know, I'll have another look when I get the chance.

**Comment by tpcyang** [comment] 2015-03-13 09:36
Got some feedback from Polish user.
It seems this bug is impacting more than a single character.

Here you can find the complete list of Polish special letters:

ęóąśłżźćń

All of them can be typed in as Right ALT + latin letter on Polish Programmers keyboard, for instance ł = Righ Alt + L

**Comment by SimeonC** [comment] 2015-04-01 23:58
I think I've fixed this this time. I've also added in a test to check this time - Triggering Alt + Ctrl + Z doesn't fire the undo command now which from what I understand is the problem.

Can someone grab the version from master and confirm this please? If not - reopen the issue please.

**Closed** 2015-04-01 23:57 UTC
Labels: bug

**Comment by akupiec** [comment] 2015-04-07 14:02
Yep it's working perfectly now.

**Comment by tongjyqueen** [comment] 2020-09-16 06:16
hi SimeonC,

I am a developer from China.
I also met this issue in my project recently. I can't type in the "ż" Polish letter.
I am very upset about this problem recently, because I don't know how to fix it. 
Can you share how you fixed it before?

I look forward to your reply

Thanks & Best Regards,
Jane

**Comment by akupiec** [comment] 2020-10-29 07:51
@tongjyqueen previews issue was fixed by #580 it was related to shortcuts capture in textAngular (I would start form checking version of the libs) ^_^
