### ISSUE TITLE
solve unexpected selection change in executing action

### ISSUE THREAD

**Issue by raffy2010** [fraywing/textAngular#1221] opened 2016-06-30 03:09 UTC
In that PR #1220  I figure out that in Chrome has the problem that clicking tool button would change the
selection to body unexpectedly. It would bring some trouble in subsequent action.

insert link, insert image, insert video and quote are influenced actions.

cache the latest selection could be a solution, if an action is executing and
window.getSelection return the element out of editing area, we just used the cache selection.
In our app, we add some custom features. click tool button, open a dialog, do some thing
and insert html string. now we need to save the selection manually, and restore it after closing
dialog.

**Comment by pbassut** [comment] 2016-06-30 03:16
Thanks! 
I'll investigate this and talk to you about the problem in order to get this merged!
Give me a few days since I'm working on something else.
Thanks for your contribution again!

**Comment by JoelParke** [comment] 2016-08-16 00:17
Please re-test with v1.5.5 which changed several things...  and then let us know...

**Comment by JoelParke** [comment] 2016-09-04 17:55
Please create a Plunkr that demonstrates this. Otherwise I will close in a while since I can't reproduce in v1.5.8.

**Closed** 2016-10-02 22:22 UTC
Labels: bug, Needs Reproduction Example
