### ISSUE TITLE
Since updating to version 1.4.3: Error: [textAngular:textAngularSetup] The textAngular-sanitize provider has been replaced by another -- have you included angular-sanitize by mistake?

### ISSUE THREAD

**Issue by Quirksmode** [fraywing/textAngular#842] opened 2015-08-13 14:56 UTC
Whilst using version 1.4.2 I noticed a bug when adding lists. I upgraded to 1.4.3 thinking this would fix the issue, but now get the following error:

Error: [textAngular:textAngularSetup] The textAngular-sanitize provider has been replaced by another -- have you included angular-sanitize by mistake?

I am using JSPM to install textAngular and had been using it with ng-sanitize which no longer seems to work, how can I fix this? 

FYI This is what I get when I run 'jspm install textAngular', I had to add ng-sanitize separately.

"textAngular": "github:fraywing/textAngular@1.4.3",

"github:fraywing/textAngular@1.4.3": {
      "angular": "github:angular/bower-angular@1.4.3",
      "css": "github:systemjs/plugin-css@0.1.13",
      "font-awesome": "npm:font-awesome@4.4.0",
      "rangy": "github:timdown/rangy-release@1.3.0"
    },

**Comment by StarpTech** [comment] 2015-08-17 23:06
same issue here with angular 1.4.4

**Comment by pbassut** [comment] 2015-08-18 00:49
Are you sure you're not including textAngular-sanitize twice?

**Comment by Quirksmode** [comment] 2015-08-18 09:40
I think it's because the latest version of Text Angular is looking for textAngular-sanitize by default, whereas before you could use the normal version. I managed to bring textAngular-sanitize in (and it works), but is there any chance you could set up your GitHub to allow for this to be installed easily via JSPM. It's such a fantastic tool and manages all the dependancies when installing. 

Ideally I would simply need to run 'jspm install textAngular' and it would generate everything I need. It's so close to working, it's just missing textAngular-sanitize

**Comment by venil7** [comment] 2015-08-19 09:16
I would like to second this issue, it exists in Angular 1.4.4.

**Comment by smajl** [comment] 2015-08-19 10:03
@Quirksmode Well, actually it is me, who did the current JSPM registry and override for textAngular and you can easily install it via JSPM. I have it installed via JSPM, does it not work for you?

If you want to use `textAngular-sanititze` just do:
```javascript
import 'textAngular';
import 'textAngular/dist/textAngular-sanitize';
```
If you want to use the regular `angular-sanitize`:
```javascript
import 'textAngular';
import 'angular-sanitize';
```
And since 1.4.3 you have to put this in your config:
```javascript
$provide.decorator('taOptions', ['taRegisterTool', '$delegate', function(taRegisterTool, taOptions) {
    ...
    taOptions.forceTextAngularSanitize = false;
    ...
    return taOptions;
  }]);
};

Tested, works. Let me know if this helps.

**Comment by JoelParke** [comment] 2015-08-29 01:38
<p>This new check/option in textAngular was added to eliminate the <b>MANY</b> issues that come about if the angular-sanitize provider is used instead of the customized textAngular sanitizer.  The standard angular ng-sanitizer is very strict and many of the tags that are essential for textAngular functionality breaks.  For example, the re-sizing of images breaks.  If that is okay, as has been suggested, setting taOptions.forceTextAngularSanitize = false, tells textAngular to ignore this.  But of course, then you will have other issues, but if that is not an issue for you application, then that is what you should do.  </p>

**Comment by JoelParke** [comment] 2015-09-02 07:12
<p>Closed this issue as it is working as designed.</p>

**Closed** 2015-09-02 07:11 UTC

**Comment by Sifis-Develop** [comment] 2015-09-08 06:55
Hello there,

i recently used textAngular with the latest version of Angular. So, i used the followed dependencies:
'textAngular.js'
'textAngularSetup.js'
'textAngular-Sanitize.js'
'textAngular-rangy.js'

The dependency of the textAngular is only in one module: angular.module('myModule', ['toaster', 'textAngular']);

So far, angular application is working nice, the problems start on my UnitTest.

I have the same dependencies as above but the message of Chutzpah (that i use) is :
"The textAngular-sanitize provider has been replaced by another -- have you included angular-sanitize by mistake?". So, i decided not to use textAngular-sanitize and replace with the original angular-sanitize making the taOptions.forceTextAngularSanitize = false;. Now the tests message does not make any sense : "Message: undefined : undefined".

Have you noticed that problem with the unit tests ? (jasmine & angular-mocks)

**Comment by JoelParke** [comment] 2015-09-09 07:43
I don't have any idea why this shows up.  If you truly are including textAngular-Sanitize.js, then you should not need to set taOptions.forceTextAngularSanitize = false, since you ARE including the textAngular-Sanitizer.  So, what happens when you don't set this false?  Do the unit tests run properly then??? and if not why not?

**Comment by pbassut** [comment] 2015-09-09 14:58
@Sifis-Develop Please, create your own issue since the problem is with unit tests. This issue was already closed

**Comment by Quirksmode** [comment] 2015-11-08 21:56
@smajl Huge thanks for the help previously with this, though have you had a problem with it since upgrading to the latest version of JSPM, I get the following errors and have no idea how to solve them, I don't suppose you have come across the same issue?

GET http://localhost:3000/static/js/app/rangy.js 404 (Not Found)I @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573
system.src.js:4573 GET http://localhost:3000/static/js/app/rangy/rangy-selectionsaverestore.js 404 (Not Found)I @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573(anonymous function) @ system.src.js:4573
localhost/:1 Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:3000/static/js/app/rangy/rangy-selectionsaverestore.js(…)t @ system.src.js:4573g @ system.src.js:4573(anonymous function) @ system.src.js:4573
system.src.js:4573 GET http://localhost:3000/static/js/app/css.js 404 (Not Found)

**Comment by smajl** [comment] 2015-11-10 10:47
@Quirksmode No problem here, running JSPM 0.16.14. Seems like your libs are not loaded from proper `jspm_packages` path (but you could have overriden this).

Make sure you have proper paths and mapping set-up in your jspm config file. Something like this:
```javascript
  ...
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  ...
  "github:fraywing/textAngular@1.4.6": {
    "angular": "github:angular/bower-angular@1.4.7",
    "css": "github:systemjs/plugin-css@0.1.19",
    "font-awesome": "npm:font-awesome@4.4.0",
    "rangy": "github:timdown/rangy-release@1.3.0"
  },
  ...
```

**Comment by Quirksmode** [comment] 2015-11-10 11:59
@smaji Huge thanks for getting back to me, that's so good to hear it's working for you, it's been driving me crazy. Would you be able to send me your full config.js so I can take a look. The paths are the issue definitely, it seems to be trying to access the files from within the root js folder, but its definitely not setup that way. One final question, do you use systemjs-builder for compiling the final compressed js file?

**Comment by smajl** [comment] 2015-11-11 13:27
@Quirksmode Sure, config is here https://gist.github.com/smajl/57abfa962b31885c1b6f and I am using directly the builder in JSPM:
```javascript
var Builder = require('jspm').Builder;
var builder = new Builder();
```
It's more convenient, because it ensures, that your JSPM set-up and builder use the same API.

**Comment by Quirksmode** [comment] 2015-11-11 13:38
Massive thanks again for this, I am going to have another look tonight, I really battled with it last night, it's so strange that it worked perfectly before the upgrade, I think I will set up a fresh environment and try from scratch.

**Comment by Quirksmode** [comment] 2015-11-13 11:33
I managed to find the cause of the problem, due to a project requirement, our backend team had moved the jspm modules to within the app folder itself and set a base URL as follows:

````javascript
<script>
    	    	System.baseURL = '/static/v0.1.0/nvcfrontend/js/app';
                System.import('modules/bootstrap');
    	    </script>
````

This always worked before the JSPM upgrade, but since then the textAngular plugin now seems to pick up the defined baseURL, which causes the problem. I am wondering how best to get around this, could I remove this baseURL and update the path to the System.import? When I try this it can no longer find the jspm packages and when I try to update the paths to these it does not seem to work. I am wondering if my syntax is wrong?

````javascript
<script>
    	    	System.paths['github:*'] = '/static/v0.1.0/nvcfrontend/js/app/jspm_packages/github/*.js';
                System.paths['npm:*'] = '/static/v0.1.0/nvcfrontend/js/app/jspm_packages/npm/*.js';
    	    	System.import('static/v0.1.0/nvcfrontend/js/app/modules/bootstrap');
    	    </script>
````

**Comment by Quirksmode** [comment] 2015-11-13 15:09
Using System.paths worked, but in doing so has brought back the exact same paths error I was having with the baseURL set. It's clearly a paths issue, that only seems to happen when using textAngular with the most recent version of JSPM loader. I am now completely lost with this, is the problem with textAngular itself? It defines the following in the main JS file. 

````javascript
/* */ 
"format global";
"deps rangy";
"deps rangy/rangy-selectionsaverestore";
"deps ./textAngularSetup";
"deps ./textAngular.css!";
/*
@license textAngular
Author : Austin Anderson
License : 2013 MIT
Version 1.4.6
````

Are the "deps" at the top ever going to work with a custom path set in JSPM? Why are they not picking the path up? I just need to know where the problem lies so I can try and figure out a fix, feel like I am going around in circles and desperate to get this sorted. Any help is massively appreciated.

**Comment by Quirksmode** [comment] 2015-11-13 19:30
To explain this further, due to a project requirement the jspm package path needs to be generated by backend, which is why I need to set the paths from the index.html where the system and config.js get definfed, I simply cannot just add the paths to the config.js.

So I managed to get this working by changing the order of when the baseURL get's set, though I am unsure on why this worked before, but not with the latest version of JSPM?

````javascript
<script src="/static/v0.1.0/nvcfrontend/js/app/jspm_packages/system.js"></script>
            <script>
                System.baseURL = '/static/v0.1.0/nvcfrontend/js/app';
            </script>
    	    <script src="/static/v0.1.0/nvcfrontend/js/app/config.js"></script>
    	    <script>
                System.import('modules/bootstrap');
    	    </script>
````

Glad there's a solution in place though, just need to fix the "angular is not defined" console error when running jspm.builder (it worked before :'-() and I can finally sleep again :-)

**Comment by shershen08** [comment] 2015-12-24 09:38
In same situation of upgrading to Angular 1.4.x - I could make module that uses textAngular to work by replacing ```ngSanitize``` to ```textAngular-sanitize```.
But then in other app module which uses ```angular-sanitize``` I start having problems!

**Comment by bmuscolino** [comment] 2017-03-29 15:59
In rails, with bower, In application.js works for me.

```
// textAngular and dependencies
//= require textAngular
//= require textAngular/dist/textAngular-sanitize
//= require textAngular/dist/textAngularSetup
//= require textAngular/dist/textAngular-rangy.min
