### ISSUE TITLE
After deleting all contents, the text area is not editable in Firefox

### ISSUE THREAD

**Issue by rdheepan** [fraywing/textAngular#1049] opened 2016-01-21 12:47 UTC
In Firefox, not able to edit the content after deleting the existing content.  
Steps to reproduce,
1. Open http://textangular.com/ in Firefox (I'm using 38.5.0 version of firefox)
2. Delete All contents in the editor
3. **Click outside once**(to get the focus out) and then click inside the editor to start editing
4. Not able to enter any text

**Comment by laudeon** [comment] 2016-01-22 16:08
I have the same issue with Firefox 43.0.4

**Comment by pbassut** [comment] 2016-01-22 16:16
What version of TA are you guys using?

**Comment by pbassut** [comment] 2016-01-22 16:18
Okay, I can reproduce this, thanks for the report. I'm fix this ASAP since it's critical

**Comment by callonravi** [comment] 2016-02-08 19:21
We are using this plugin. It has been so helpful. It would be nice to get this fixed. Thanks for your support!!!

**Comment by matt-major** [comment] 2016-02-22 10:11
Any update on when this might be fixed, please?

I've been able to replicate in Firefox v43.0.4 and v44.0.2 on both Windows and OS X.

**Comment by mikeagoff** [comment] 2016-03-03 15:29
While waiting for this to be fixed, you could also add logic to check if the element is empty and add `<p></p>` tags. 
`if(angular.element("div.ta-bind).html() == ""){
   angular.element('div.ta-bind').append('<p></p>')
}`

**Comment by JoelParke** [comment] 2016-08-06 18:48
I believe this is fixed with release v1.5.4 -- please reopen if not!!

**Closed by JoelParke** 2016-08-06 18:48 UTC
Labels: bug
