### ISSUE TITLE
Lines break when copy-pasting between 2 textAngular instances

### ISSUE THREAD

**Issue by DavidVentura** [fraywing/textAngular#1155] opened 2016-04-18 21:14 UTC
So, If I copy from an existing editor to a new editor my lines get broken pretty arbitrarily.

This line (with no formatting)
```
El tratamiento tópico es aceptado para el acné leve y moderado, mientras que el acné más grave requiere la introducción de un tratamiento oral. 
```
gets broken to:
```
El<br>
&nbsp;tratamiento tópico es aceptado para el acné leve y moderado, mientras <br>
que el acné más grave requiere la introducción de un tratamiento oral. <br>
```

Notice the initial, arbitrary line-break after the first word. **WHY?**
Then I get another arbitrary line-break after 78 characters.

This is on textAngular 1.5(latest release). Let me know if you need more info

![copy1](https://cloud.githubusercontent.com/assets/3650670/14620004/d35bb52a-0590-11e6-8a81-e9b53b9a761a.png)
![copy2](https://cloud.githubusercontent.com/assets/3650670/14620005/d3666f2e-0590-11e6-968d-4be1c4dde2ba.png)

**Comment by pbassut** [comment] 2016-04-19 19:05
That depends where you copying that from. Maybe the paste chunk has information that leads textAngular to parse it incorrectly thinking it's a specific provided(OneNote, Word, Notes, etc)?

**Comment by DavidVentura** [comment] 2016-04-19 19:06
Copying from:
Word
HTML
plain text

triggers this

On 19 April 2016 at 16:05, Patrick Bassut <notifications@github.com> wrote:

> That depends where you copying that from. Maybe the paste chunk has
> information that leads textAngular to parse it incorrectly thinking it's a
> specific provided(OneNote, Word, Notes, etc)?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/fraywing/textAngular/issues/1155#issuecomment-212071598>
>



-- 
*Stack* is the new term for "I have no idea what I'm actually using".

**Comment by DavidVentura** [comment] 2016-04-24 00:59
So, copying your answer from github (that shouldn't match  `/\r|\r\n|\n/` ) 

"That depends where you copying that from. Maybe the paste chunk has information that leads textAngular to parse it incorrectly thinking it's a specific provided(OneNote, Word, Notes, etc)?"

triggers the replace on line 1613
```
text=text.replace(/\n|\r\n|\r/g, '<br />');
```

**Comment by pbassut** [comment] 2016-04-24 18:30
Looks like I can't reproduce this in any way. I'm trying on textAngular.com 
Tell me more about your setup.
Browser, OS, Version of textAngular(you said it's latest).

**Comment by DavidVentura** [comment] 2016-04-24 21:42
Happens to me on textAngular.com. Firefox on linux, On my site I'm using 1.5.0
https://gfycat.com/ScarceInsistentCorydorascatfish

**Comment by DavidVentura** [comment] 2016-04-25 18:32
What do you need for 'reproduction example'? I linked you a video of me copying from github to textAngular.com and showing how it broke, along with the line detecting line-breaks that are not there. How can I help you fix this faster?

**Comment by pbassut** [comment] 2016-04-25 18:58
sorry, I thought it was an example to paste. You didn't mention it was a video.
Thanks for the reproduction example. I'll set up an windows 8 machine with firefox to reproduce the issue.

**Comment by vepanimas** [comment] 2016-07-07 21:34
I've found the reason, you can check it on this [jsfiddle ](https://jsfiddle.net/acapwt04/).

When 'paste' event triggered, its clipboardData may contain 'text/html' content ([code link](https://github.com/fraywing/textAngular/blob/master/src/taBind.js#L684)). In this case `pastedContent` variable will contain something like that:

```html
<html>
<body>
<!--StartFragment-->
pasted text
<!--EndFragment-->
</body>
</html>
```

Stringified it looks like:
```html
"<html>\r\n<body>\r\n<!--StartFragment-->pasted text<!--EndFragment-->\r\n</body>\r\n</html>"
```

So, on the next step [this code](https://github.com/fraywing/textAngular/blob/master/src/taBind.js#L645) replaces our `\r\n` symbols to `<br />`.

Chrome browser adds `\r\n` symbols, Firefox adds only `\n` symbol between these lines. I think, we should remove these linebreaks first.

This issue is very critical, I would be very grateful if you will fix it as soon as possible.

**Comment by cmacdonnacha** [comment] 2016-07-18 15:50
+1

**Comment by RDMEC** [comment] 2016-08-01 14:42
+1

**Comment by hl-away** [comment] 2016-08-30 10:54
+1

**Comment by JoelParke** [comment] 2016-09-16 06:47
<p>I clearly see the issue when using the supplied <span style="font-size: 14px;float: none;"> </span><a href="https://jsfiddle.net/acapwt04/" style="color: rgb(66, 139, 202);font-size: 14px;">jsfiddle</a>.  I have one <a href="https://jsfiddle.net/acapwt04/" style="color: rgb(66, 139, 202);font-size: 14px;">jsfiddle</a> running on Chrome and one running on Firefox.</p><p>When I copy from the Chrome instance to the Firefox instance I see this markup:</p><pre>​&#34;&lt;meta http-equiv=\&#34;content-type\&#34; content=\&#34;text/html; <br/>charset=utf-8\&#34;&gt;&lt;h1 style=\&#34;color: rgb(0, 0, 0); font-family: <br/>&amp;quot;Times New Roman&amp;quot;; font-style: normal; <br/>font-variant-ligatures: normal; font-variant-caps: normal; <br/>letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px;<br/> text-transform: none; white-space: normal; widows: 2; word-spacing: <br/>0px; -webkit-text-stroke-width: 0px;\&#34;&gt;Copy this markup to content <br/>editable&lt;/h1&gt;&lt;span style=\&#34;color: rgb(0, 0, 0); font-family: <br/>&amp;quot;Times New Roman&amp;quot;; font-size: medium; font-style: <br/>normal; font-variant-ligatures: normal; font-variant-caps: normal; <br/>font-weight: normal; letter-spacing: normal; orphans: 2; text-align: <br/>start; text-indent: 0px; text-transform: none; white-space: normal; <br/>widows: 2; word-spacing: 0px; -webkit-text-stroke-width: <br/>0px;\&#34;&gt;123123&lt;/span&gt;\u0000&#34;</pre><p>And when I copy from the Firefox instance I see this markup:</p><pre>​&#34;&lt;h1&gt;Copy this markup to content editable&lt;/h1&gt;\n &lt;span&gt;123123&lt;/span&gt;&#34;</pre><p>NEXT I brought up the current v1.5.9 TA: <a href="http://textangular.com/" target="">http://textangular.com/</a> on Firefox and copied from the <a href="https://jsfiddle.net/acapwt04/" style="color: rgb(66, 139, 202);font-size: 14px;">jsfiddle</a> on Chome.<br/>AND I see:</p><pre class="white-box ng-binding">&lt;h1&gt;Copy this markup to content editable&lt;/h1&gt;&lt;p&gt;123123&lt;/p&gt;</pre><p>which is correct .. and radically different that the Chrome to Firefox above.</p><p>Going the other way from <a href="https://jsfiddle.net/acapwt04/" style="color: rgb(66, 139, 202);font-size: 14px;">jsfiddle</a> on Firefox to <a href="http://textangular.com/" target="" style="color: rgb(42, 100, 150);text-decoration: underline;font-size: 14px;">http://textangular.com/</a> on Chrome I see:</p><pre class="white-box ng-binding" style="font-size: 13px;">&lt;h1&gt;Copy this markup to content editable&lt;/h1&gt;&lt;p&gt;&lt;br/&gt;&lt;/p&gt;&lt;p&gt;&lt;span&gt;123123&lt;/span&gt;&lt;/p&gt;</pre><p>NEXT going from <a href="http://textangular.com/" target="" style="color: rgb(42, 100, 150);text-decoration: underline;font-size: 14px;">http://textangular.com/</a> on Firefox to <a href="http://textangular.com/" target="" style="color: rgb(42, 100, 150);text-decoration: underline;font-size: 14px;">http://textangular.com/</a> on Chrome I see: </p><pre class="white-box ng-binding" style="font-size: 13px;">&lt;h1&gt;Copy this markup to content editable&lt;/h1&gt;&lt;p&gt;123123&lt;/p&gt;</pre><p>THEN going from <a href="http://textangular.com/" target="" style="color: rgb(42, 100, 150);text-decoration: underline;font-size: 14px;">http://textangular.com/</a> on Chrome to <a href="http://textangular.com/" target="" style="color: rgb(42, 100, 150);text-decoration: underline;font-size: 14px;">http://textangular.com/</a> on Firefox I see:</p><pre class="white-box ng-binding">&lt;h1 style=&#34;font-size: 36px;&#34;&gt;Copy this markup to content editable&lt;/h1&gt;&lt;p&gt;&lt;span style=&#34;font-size: 14px;&#34;&gt;123123&lt;/span&gt;&lt;/p&gt;</pre><p>So I think on TA v1.5.9 this is about what I would expect.</p><p>I am going to close this now ... In the hopes that IF it is still broken you can reproduce and re-open...  Sorry that it took so long for me to get to this, but I am trying to close out a bunch of bugs in the coming weeks.</p><p>NOTE: I did all my testing for this on Ubuntu 16.04</p>

**Closed** 2016-09-16 06:48 UTC
Labels: bug, Critical, duplicate

**Comment by vepanimas** [comment] 2016-09-16 16:58
It is still broken, even on the http://textangular.com/ 1.5.9. It looks like a platform issue, on Linux it works properly, on Windows (I test it on Windows 10) it doesn't. We should remove unnecessary linebreaks before replacing them with <br />.

I wrote some text, and then cut it out and pasted it back. The result is below:

![ta-issue](https://cloud.githubusercontent.com/assets/10243762/18594164/4105e76c-7c47-11e6-98fa-46dbd04f5bb9.gif)

**Comment by ReFury** [comment] 2016-10-25 10:43
`.replace(/\n|\r\n|\r/g, '<p>')`

works fine i think.
