### ISSUE TITLE
Wrong positioning of popover after scrolling

### ISSUE THREAD

**Issue by lostip** [fraywing/textAngular#299] opened 2014-08-29 22:58 UTC
When calling editorScope.showPopover(element), scroll position is not considered for positioning the popover.
Please see attached screenshots to see an example where no scrolling has occurred, and one where it has (this is a custom tool, but I'm using the provided popover).
Also, here's a diff with a possible fix, where the scrollTop is subtracted from the calculated top position in the reflowPopover function:
```
			scope.reflowPopover = function(_el){
				if(scope.displayElements.text[0].offsetHeight - 51 > _el[0].offsetTop){
-					scope.displayElements.popover.css('top', _el[0].offsetTop + _el[0].offsetHeight + 'px');
+					scope.displayElements.popover.css('top', _el[0].offsetTop + _el[0].offsetHeight - scope.displayElements.scrollWindow[0].scrollTop + 'px');
					scope.displayElements.popover.removeClass('top').addClass('bottom');
				}else{
-					scope.displayElements.popover.css('top', _el[0].offsetTop - 54 + 'px');
+					scope.displayElements.popover.css('top', _el[0].offsetTop - 54 - scope.displayElements.scrollWindow[0].scrollTop + 'px');
					scope.displayElements.popover.removeClass('bottom').addClass('top');
				}
				var _maxLeft = scope.displayElements.text[0].offsetWidth - scope.displayElements.popover[0].offsetWidth;
```

![no-scroll](https://cloud.githubusercontent.com/assets/572961/4097123/97c1c33c-2fcd-11e4-9a3d-e36521e83f90.png)
![with-scroll](https://cloud.githubusercontent.com/assets/572961/4097121/9788ffca-2fcd-11e4-82f5-5985d0a41ee7.png)

**Comment by SimeonC** [comment] 2015-03-01 23:41
@lostip It's taken me a while to get back around to this - adding in the fix you mentioned earlier seems to work OK, but I don't have any CSS to test this with. I can commit based off your diff if you can confirm that that would fix your issue, but I would like to be able to test it myself.

**Comment by lostip** [comment] 2015-03-03 18:50
@SimeonC let me put together a plunkr or something like that so you can test this better. 
I'll try to have tomorrow or the day after.
Thanks for looking into this!

**Comment by SimeonC** [comment] 2015-03-13 05:00
This should be patched in 1.3.8, I think. So if when you get around to testing this do it on that tag please.

**Comment by pbassut** [comment] 2015-08-04 19:22
@lostip Could you setup a plnkr so we can update this issue?

Thanks a lot.

**Comment by hiretheheir** [comment] 2016-02-22 13:33
Issue reproduced at [Plnkr](http://plnkr.co/edit/2xXMRowAqTNxDMv9rS2B?p=preview)
This is how the reflowPopover function looks like:

```
scope.reflowPopover = function(_el) {
    if (_el[0].closest) {
        var scrollLength = _el[0].closest('.ta-bind').scrollTop;
    } else {
        var scrollLength = $(_el[0]).closest('.ta-bind')[0].scrollTop;
    }

    /* istanbul ignore if: catches only if near bottom of editor */
    if (scope.displayElements.text[0].offsetHeight - 51 > _el[0].offsetTop) {
        //scope.displayElements.popover.css('top', _el[0].offsetTop + _el[0].offsetHeight + scope.displayElements.scrollWindow[0].scrollTop - scrollLength + 'px');	
        scope.displayElements.popover.css('top', _el[0].offsetTop + _el[0].offsetHeight + scope.displayElements.scrollWindow[0].scrollTop - scope.displayElements.scrollWindow[0].scrollTop + 'px');
        scope.displayElements.popover.removeClass('top').addClass('bottom');
    } else {
        //scope.displayElements.popover.css('top', _el[0].offsetTop - 54 + scope.displayElements.scrollWindow[0].scrollTop - scrollLength + 'px');
        scope.displayElements.popover.css('top', _el[0].offsetTop - 54 + scope.displayElements.scrollWindow[0].scrollTop - scope.displayElements.scrollWindow[0].scrollTop + 'px');
        scope.displayElements.popover.removeClass('bottom').addClass('top');
    }
    var _maxLeft = scope.displayElements.text[0].offsetWidth - scope.displayElements.popover[0].offsetWidth;
    var _targetLeft = _el[0].offsetLeft + (_el[0].offsetWidth / 2.0) - (scope.displayElements.popover[0].offsetWidth / 2.0);
    scope.displayElements.popover.css('left', Math.max(0, Math.min(_maxLeft, _targetLeft)) + 'px');
    scope.displayElements.popoverArrow.css('margin-left', (Math.min(_targetLeft, (Math.max(0, _targetLeft - _maxLeft))) - 11) + 'px');
};

```
So basically I had to negate the addition of scope.displayElements.scrollWindow[0].scrollTop with itself (which amounts to zero px). Which means that the code before @lostip code was committed was just fine.

I maybe wrong about it, but currently that is what is working for me.

**Comment by JoelParke** [comment] 2016-10-02 07:39
Corrected this with PR #1349. Closing - please test...

**Closed by JoelParke** 2016-10-02 07:39 UTC
Labels: bug

**Comment by jaimeschettini** [comment] 2016-10-10 14:31
Hello, I'm having the same problem here and seems that PR #1349 hasn't solved it. I also tested in this [plucker](http://plnkr.co/edit/9y1gJyJcfu3yu346vrsY?p=preview) which I forked from the one created by @hiretheheir and just changed the version of textAngular to 1.5.12.

**Comment by LeonadoRivaldo** [comment] 2017-05-18 12:25
hi, i have the same problem and i find a math problem inside the reflowPopover function, só i ll leave here the code that work for as a suggestion to fix the problem.
`                    if(spaceAboveImage < 51) {
                        //original line
                        //scope.displayElements.popover.css('top', _el[0].offsetTop + _el[0].offsetHeight + scope.displayElements.scrollWindow[0].scrollTop + 'px');
                        //correction
                        scope.displayElements.popover.css('top', _el[0].offsetTop + _el[0].offsetHeight + 'px');
                        scope.displayElements.popover.removeClass('top').addClass('bottom');
                    } else {
                        //origirnal line
                        //scope.displayElements.popover.css('top', _el[0].offsetTop - 54 + scope.displayElements.scrollWindow[0].scrollTop + 'px');
                        //correction
                        scope.displayElements.popover.css('top', _el[0].offsetTop - 54 + 'px');

                        scope.displayElements.popover.removeClass('bottom').addClass('top');
                    }`

**Comment by LeonadoRivaldo** [comment] 2017-05-18 12:26
hi, i have the same problem and i find a math problem inside the reflowPopover function, só i ll leave here the code that work for as a suggestion to fix the problem.
`if(spaceAboveImage < 51) {
//original line
//scope.displayElements.popover.css('top', _el[0].offsetTop + _el[0].offsetHeight + scope.displayElements.scrollWindow[0].scrollTop + 'px');
//correction
scope.displayElements.popover.css('top', _el[0].offsetTop + _el[0].offsetHeight + 'px');
scope.displayElements.popover.removeClass('top').addClass('bottom');
} else {
//origirnal line
//scope.displayElements.popover.css('top', _el[0].offsetTop - 54 + scope.displayElements.scrollWindow[0].scrollTop + 'px');
//correction
scope.displayElements.popover.css('top', _el[0].offsetTop - 54 + 'px');
scope.displayElements.popover.removeClass('bottom').addClass('top');
}`

**Comment by LeonadoRivaldo** [comment] 2017-05-18 12:27
hi, i have the same problem and i find a math problem inside the reflowPopover function, só i ll leave here the code that work for as a suggestion to fix the problem.
`
if(spaceAboveImage < 51) {
	//original line
	//scope.displayElements.popover.css('top', _el[0].offsetTop + _el[0].offsetHeight + scope.displayElements.scrollWindow[0].scrollTop + 'px');
	//correction
	scope.displayElements.popover.css('top', _el[0].offsetTop + _el[0].offsetHeight + 'px');
	scope.displayElements.popover.removeClass('top').addClass('bottom');
} else {
	//origirnal line
	//scope.displayElements.popover.css('top', _el[0].offsetTop - 54 + scope.displayElements.scrollWindow[0].scrollTop + 'px');
	//correction
	scope.displayElements.popover.css('top', _el[0].offsetTop - 54 + 'px');
	scope.displayElements.popover.removeClass('bottom').addClass('top');
}`

**Comment by LeonadoRivaldo** [comment] 2017-05-18 12:30
hi, i have the same problem and i find a math problem inside the reflowPopover function, só i ll leave here the code that work for me as a suggestion to fix the problem.
```
if(spaceAboveImage < 51) {
	//original line
	//scope.displayElements.popover.css('top', _el[0].offsetTop + _el[0].offsetHeight + scope.displayElements.scrollWindow[0].scrollTop + 'px');
	//correction
	scope.displayElements.popover.css('top', _el[0].offsetTop + _el[0].offsetHeight + 'px');
	scope.displayElements.popover.removeClass('top').addClass('bottom');
} else {
	//origirnal line
	//scope.displayElements.popover.css('top', _el[0].offsetTop - 54 + scope.displayElements.scrollWindow[0].scrollTop + 'px');
	//correction
	scope.displayElements.popover.css('top', _el[0].offsetTop - 54 + 'px');
	scope.displayElements.popover.removeClass('bottom').addClass('top');
}
```

**Comment by pranav-pkasthana** [comment] 2022-01-17 07:29
for me setting the below option inside div worked
popover-append-to-body="false"
