### ISSUE TITLE
Disabling either Bold or Italic when both are selected on an empty new line

### ISSUE THREAD

**Issue by mimarcos** [fraywing/textAngular#1105] opened 2016-03-10 15:59 UTC
Small issue that we've been working around. When you are typing text that is formatted with both bold and italic (I presume other formats as well, basically more than one), and you end a line by hitting return, the text formatting remains on the new line, and cannot be disabled without selecting text.

This is present in any demo of TA, including the demo page.

Reproduction steps would be:

1) Turn on bold.
2) Turn on italic.
3) Type some text.
4) New paragraph by hitting enter
  - A new paragraph is inserted and bold/italic remain enabled
5) Try turning off bold or italic formatting

**Comment by JoelParke** [comment] 2016-08-17 22:07
I see the issue even with v1.5.6-0.  I will look at it when I get a chance.  The issue is that this comes from what the browser tells us... and so it may not be fixable... I will report back.

**Comment by JoelParke** [comment] 2016-08-25 20:44
This is mostly fixed with PR #1289 and actually a rangy bug.

**Closed by JoelParke** 2016-08-25 20:44 UTC
Labels: bug
