### ISSUE TITLE
Error: removeCSSRule results in "Invalid argument"

### ISSUE THREAD

**Issue by snekbaev** [fraywing/textAngular#543] opened 2015-02-11 13:11 UTC
Hi,

I add TA's in ng-repeat, just mentioned that I get that error. I don't have a plunkr neither more details at the moment. The way I fixed it:

```
_removeCSSRule = function (sheet, index) {
            /* istanbul ignore else: untestable IE option */
            if (sheet.removeRule) {
                if (sheet.rules[index]) {
                    sheet.removeRule(index);
                }
            } else {
                sheet.deleteRule(index);
            }
        };
```
If you could confirm that it doesn't break anything, maybe then it could be added to the sources, though I bet you want to investigate first how come a rule that you expect to exist doesn't exist in the first place :)
P.S.: IE11, 1.3.0-23

UPDATE: had a wrong check for the second ```if``` statement

**Comment by SimeonC** [comment] 2015-02-19 21:24
I actually ran into this the other day, yes that's the simple fix.

The problem is if you add textAngular editors in this order: A, B, C. Then Remove B, then remove C, you'll get this error as it tries remove the rule at index 1, making the length 2 then trying to remove the rule at index 2, which doesn't exist anymore :(

**Comment by snekbaev** [comment] 2015-02-19 21:35
Hi,

thank you for replying. Good to know you were aware of this. If ```removeRule()``` works against ```rules``` array then yeah, this seems to be it :) hopefully fix will appear in the upcoming release. Thanks again!

**Comment by SimeonC** [comment] 2015-05-23 15:02
This should be fixed in master now.

**Closed by SimeonC** 2015-05-23 15:02 UTC
Labels: bug
