### ISSUE TITLE
v1.3.1 error because rangy minfiy dont contain - window.rangy 

### ISSUE THREAD

**Issue by eladh** [fraywing/textAngular#510] opened 2015-01-26 07:59 UTC
getting the following error : 

Uncaught rangy-core.js and rangy-selectionsaverestore.js are required for textAngular to work correctly, rangy-core is not yet loaded. 

10x

**Comment by SimeonC** [comment] 2015-01-26 21:15
Thanks, I've had some problems with rangy of recent due to the rangy bower tag changing names/authors/repositories and all sorts of other mess.

I'll be looking into this ASAP.

**Comment by SimeonC** [comment] 2015-01-26 22:18
Ok, I've checked up with the dependancies. Should be fixed in the 1.3.2 version.

**Closed by SimeonC** 2015-01-26 22:18 UTC

**Comment by FiremanPass** [comment] 2015-05-27 13:31
Getting the same exception with textAngular version 1.4.1 could it be a regression bug?
