### ISSUE TITLE
Error: Module failed to find node module rangy (ReferenceError: Can't find variable: require)

### ISSUE THREAD

**Issue by jeffreybraun** [fraywing/textAngular#867] opened 2015-09-10 20:25 UTC
I'm using angular 1.4.5, font-awesome 4.4.0, rangy 1.3.0, gulp 3.9.0, and textAngular 1.4.3.

I really like the textAngular component, and it’s working just fine when I run it with “gulp serve”.
But as soon as I had the control working, my entire test suite started failing.
I was able to address many of the errors, but I feel a little stuck with what is hopefully the final issue.

I received the following error when running “gulp test”:
>      INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
>      INFO [launcher]: Starting browser PhantomJS
>      INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket E9wK3TqONrQFDk5jrL_5 with id 3837107
>      PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
>        ReferenceError: Can't find variable: require
>        at /Users/jeff/workspace/OCAT_Server/client/bower_components/textAngular/dist/textAngular-rangy.min.js:2

Since the error message indicates it wanted "require" for the textAngular-rangy script, I downloaded RequireJS (version 2.1.20) via Bower, even though this not considered to be a Bower dependency for textAngular.

I added the following line to to my karma.conf.js file:
>      path.join(conf.paths.bower_components, 'require/build/require.js’),

And now I'm getting this new error:
>      INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
>      INFO [launcher]: Starting browser PhantomJS
>      INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket cdAuAw1LXffvDnJisP3o with id 43015370
>      WARN [web-server]: 404: /node_modules/rangy/package.json
>      WARN [web-server]: 404: /node_modules/rangy/package.json
>      WARN [web-server]: 404: /node_modules/rangy/package.json
>      PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
>        Error: Module failed to find node module rangy
>        at /Users/jeff/workspace/OCAT_Server/client/bower_components/require/build/require.js:558

At this point I'm a little stuck as to what to do next.

Here's my listFiles routine in the karma.config.js file:
>    function listFiles() {
>      return [
>        path.join(conf.paths.bower_components, 'jquery/dist/jquery.js'),
>        path.join(conf.paths.bower_components, 'angular/angular.js'),
>        path.join(conf.paths.bower_components, 'angular-bootstrap/ui-bootstrap-tpls.js'),
>        path.join(conf.paths.bower_components, 'bootstrap/dist/js/bootstrap.js'),
>        path.join(conf.paths.bower_components, 'angular-sanitize/angular-sanitize.js'),
>        path.join(conf.paths.bower_components, 'angular-translate/angular-translate.js'),
>        path.join(conf.paths.bower_components, 'angular-dialog-service/dist/dialogs.min.js'),
>        path.join(conf.paths.bower_components, 'angular-dialog-service/dist/dialogs-default-translations.min.js'),
>        path.join(conf.paths.bower_components, 'angular-resource/angular-resource.js'),
>        path.join(conf.paths.bower_components, 'angular-ui-bootstrap-datetimepicker/datetimepicker.js'),
>        path.join(conf.paths.bower_components, 'angular-ui-router/release/angular-ui-router.js'),
>        path.join(conf.paths.bower_components, 'moment/moment.js'),
>        path.join(conf.paths.bower_components, 'angular-mocks/angular-mocks.js'),
>        path.join(conf.paths.bower_components, 'require/build/require.js'),
>        path.join(conf.paths.bower_components, 'rangy/rangy-core.min.js'),
>        path.join(conf.paths.bower_components, 'rangy/rangy-selectionsaverestore.min.js'),
>        path.join(conf.paths.bower_components, 'textAngular/dist/textAngularSetup.js'),
>        path.join(conf.paths.bower_components, 'textAngular/dist/textAngular-rangy.min.js'),
>        path.join(conf.paths.bower_components, 'textAngular/dist/textAngular-sanitize.min.js'),
>        path.join(conf.paths.bower_components, 'textAngular/dist/textAngular.min.js'),
>        path.join(conf.paths.src, '/app/**/*.module.js'),
>        path.join(conf.paths.src, '/app/**/*.js'),
>        path.join(conf.paths.src, '/**/*.spec.js'),
>        path.join(conf.paths.src, '/**/*.mock.js'),
>        path.join(conf.paths.src, '/**/*.html')
>      ];
>    }

I hope someone can help me. Like I said, I really like textAngular; but I won't be able to use this component as long as the tests are failing.

Please let me know what other information you need. I'm eager for a solution to my problem. Thanks!

Jeff

**Comment by pbassut** [comment] 2015-09-11 16:45
As you said, requireJS is not a dependency for TA(until the next version because we're now supporting requireJS).
Maybe that's the case. So, get our very latest commit code to see if it solves the issue for you. If it does, you'll have to wait until 1.4.4. If it doesn't, let me know.

**Comment by jeffreybraun** [comment] 2015-09-11 20:52
Thanks so much for replying. I really want to use textAngular (it has a nice look and feel), but it also appears it's the only game in town. I can't find any Rich-Text editors in Angular other than textAngular.

Do you know which JS package the "require" function reference in textAngular-rangy.min.js is suppose to be coming from if not RequireJS? Looks like this problem was introduced with 1.4.0, because I get this error for all available 1.4.X versions of textAngular (1.4.0, 1.4.1, 1.4.2, 1.4.3). If I revert to 1.3.11 the tests start working again, but the component is screwed up on the page (some of the toolbar doesn't appear correctly, and it's only a single line tall), and I get a strange mysterious text box showing up on the bottom of all of my pages.

**Comment by pbassut** [comment] 2015-09-11 21:23
requireJS is a library that allows you to load modules. Are you using requireJS(commonJS)? If so, you need wait until the next release. So, there's a few tweaks you must do to get it working(for example, TA searches for rangy in the global scope even though when using requireJS. Thus, breaking things). So, the tweak is for looking in global scope and then using requireJS if it's not there.

About the bugs, it's possibly a bug we resolved and you're with bad luck when choosing a version to revert to.

Did I answer your question correctly? If not, please let me know. 
Thanks for reporting this anyway.

**Comment by jeffreybraun** [comment] 2015-09-11 21:46
I was not using RequireJS until I saw the error message, and then I installed it via Bower as a means to deal with this problem, which lead to the next issue. From my standpoint I have no need/desire to use RequireJS. 
I'm not sure how to get rangy into the global scope for running tests, but this sounds promising. I'm guessing this must be why it works via "gulp serve", but is failing with when I do "gulp test" because Karma and/or PhantomJS don't have it in their global scope. (I'm not a testing expert, so I'm just guessing a little here what handles the global scope in this case.)

Can you point me in the correct direction for getting rangy into the global scope for my tests? 

Thanks!

**Comment by pbassut** [comment] 2015-09-11 21:51
Is rangy on you're node_modules?

**Comment by jeffreybraun** [comment] 2015-09-11 22:35
I'm referencing rangy via my bower_components directory. You can see my listFiles from the karma.config.js file above in my original post, but here are the rangy lines again:

>path.join(conf.paths.bower_components, 'rangy/rangy-core.min.js'),
>path.join(conf.paths.bower_components, 'rangy/rangy-selectionsaverestore.min.js'),

If it's installed via Bower or NPM, I'd *think* the location of rangy wouldn't matter as long as it's referenced in the karma.config.js correctly. (But I'm willing to be wrong in this case.)

**Comment by jeffreybraun** [comment] 2015-09-11 22:55
I went ahead an installed it via NPM (besides my Bower install). 
>npm install rangy --save
>npm WARN package.json chicagoPublicMediaCms@0.0.0 No repository field.
>npm WARN package.json chicagoPublicMediaCms@0.0.0 No license field.
>rangy@1.3.0 node_modules/rangy

Still getting the same error, but I'm guessing I need to reference the node_modules location in my karma.config.js.

**Comment by pbassut** [comment] 2015-09-11 23:01
That's right. Let me know what you find out.

**Comment by jeffreybraun** [comment] 2015-09-12 00:49
Unfortunately, I added the rangy files from the node_modules directory to my karma path, and got the same error.

**Comment by pbassut** [comment] 2015-09-12 16:41
upgrade to 1.4.4 and see it that solves your issue. If not, please provide the code that's breaking so I can reproduce and look further for the bug.

**Comment by JoelParke** [comment] 2015-09-12 23:50
Note there is a new version of 1.4.4 out there now, so please use that one.

**Comment by pbassut** [comment] 2015-09-12 23:56
This is the same as #871. Which have been solved. I'm closing this, then.

**Closed by pbassut** 2015-09-12 23:56 UTC
