### ISSUE TITLE
Format tools: toggle incorrectly

### ISSUE THREAD

**Issue by hengsokly** [fraywing/textAngular#603] opened 2015-03-30 03:46 UTC
When I focus on the text angular, and click on "Bold" tab then it is active. However, without inputing any text, it is still active event I click on it again in order to be inactive on the tab.

**Comment by andreaslarssen** [comment] 2015-06-04 05:27
Button toggling is not working. To write in bold, you have to mark text, then click bold. Is this expected behaviour?

**Comment by sergonius** [comment] 2016-03-09 07:53
Case: empty blurred editor.
Expectation: When I click on a button in the toolbar, the editor becomes active and the selected style is applied.
Reality: Nothing happens. The editor is still inactive.

Another thing:
When you click on the textarea first, the editor becomes active, and there another fun things happens. The textarea is empty. You click on a button, the editor becomes inactive (what?). OK, lets try that again. You click on the textarea to focus the editor again, click on the button and voilá, it works (but on the second try...).

This needs to be fixed.

**Comment by pbassut** [comment] 2016-03-27 17:39
@sergonius This issue already exists somewhere but I can't find it. But still you should create another issue since that bug you reported has nothing to do with the original issue. 
Please, do that.

**Comment by JoelParke** [comment] 2016-08-25 20:39
This is mostly fixed with PR #1289 and actually a rangy bug.

**Closed by JoelParke** 2016-08-25 20:39 UTC
Labels: bug
